// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peerflow.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope_MessageType int32

const (
	Envelope_UNKNOWN       Envelope_MessageType = 0
	Envelope_HANDSHAKE_REQ Envelope_MessageType = 1 // Send inventory of notes
	Envelope_HANDSHAKE_RES Envelope_MessageType = 2 // Respond with inventory and/or send note updates
	Envelope_NOTE_SYNC     Envelope_MessageType = 3 // Synchronize a text delta or full note
	Envelope_FILE_TRANSFER Envelope_MessageType = 4 // [Future] Transfer of binary blocks (images/files)
)

// Enum value maps for Envelope_MessageType.
var (
	Envelope_MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "HANDSHAKE_REQ",
		2: "HANDSHAKE_RES",
		3: "NOTE_SYNC",
		4: "FILE_TRANSFER",
	}
	Envelope_MessageType_value = map[string]int32{
		"UNKNOWN":       0,
		"HANDSHAKE_REQ": 1,
		"HANDSHAKE_RES": 2,
		"NOTE_SYNC":     3,
		"FILE_TRANSFER": 4,
	}
)

func (x Envelope_MessageType) Enum() *Envelope_MessageType {
	p := new(Envelope_MessageType)
	*p = x
	return p
}

func (x Envelope_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Envelope_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_peerflow_proto_enumTypes[0].Descriptor()
}

func (Envelope_MessageType) Type() protoreflect.EnumType {
	return &file_peerflow_proto_enumTypes[0]
}

func (x Envelope_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Envelope_MessageType.Descriptor instead.
func (Envelope_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_peerflow_proto_rawDescGZIP(), []int{0, 0}
}

// Generic wrapper for all P2P messages
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  Envelope_MessageType   `protobuf:"varint,1,opt,name=type,proto3,enum=peerflow.Envelope_MessageType" json:"type,omitempty"`
	// Serialized bytes of the corresponding message type
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_peerflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_peerflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_peerflow_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() Envelope_MessageType {
	if x != nil {
		return x.Type
	}
	return Envelope_UNKNOWN
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Handshake: Exchange current state to determine the delta sync needed
type Handshake struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PeerId         string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`                                                                                                    // Our unique Peer ID
	NoteTimestamps map[string]int64       `protobuf:"bytes,2,rep,name=note_timestamps,json=noteTimestamps,proto3" json:"note_timestamps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Map of Note_ID -> Unix timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_peerflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_peerflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_peerflow_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Handshake) GetNoteTimestamps() map[string]int64 {
	if x != nil {
		return x.NoteTimestamps
	}
	return nil
}

// Note Synchronization (Last-Write-Wins strategy)
type NoteSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // Timestamp of the last modification (LWW)
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                       // Text content of the note
	IsDeleted     bool                   `protobuf:"varint,4,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"` // Tombstone flag to handle deletions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteSync) Reset() {
	*x = NoteSync{}
	mi := &file_peerflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteSync) ProtoMessage() {}

func (x *NoteSync) ProtoReflect() protoreflect.Message {
	mi := &file_peerflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteSync.ProtoReflect.Descriptor instead.
func (*NoteSync) Descriptor() ([]byte, []int) {
	return file_peerflow_proto_rawDescGZIP(), []int{2}
}

func (x *NoteSync) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *NoteSync) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NoteSync) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NoteSync) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

// [Future] Payload for Clipboard Sharing or Heavy File Transfers
type FileTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	ChunkOffset   int64                  `protobuf:"varint,4,opt,name=chunk_offset,json=chunkOffset,proto3" json:"chunk_offset,omitempty"`
	ChunkData     []byte                 `protobuf:"bytes,5,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransfer) Reset() {
	*x = FileTransfer{}
	mi := &file_peerflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransfer) ProtoMessage() {}

func (x *FileTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_peerflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransfer.ProtoReflect.Descriptor instead.
func (*FileTransfer) Descriptor() ([]byte, []int) {
	return file_peerflow_proto_rawDescGZIP(), []int{3}
}

func (x *FileTransfer) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileTransfer) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileTransfer) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FileTransfer) GetChunkOffset() int64 {
	if x != nil {
		return x.ChunkOffset
	}
	return 0
}

func (x *FileTransfer) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

var File_peerflow_proto protoreflect.FileDescriptor

const file_peerflow_proto_rawDesc = "" +
	"\n" +
	"\x0epeerflow.proto\x12\bpeerflow\"\xbc\x01\n" +
	"\bEnvelope\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.peerflow.Envelope.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"b\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x11\n" +
	"\rHANDSHAKE_REQ\x10\x01\x12\x11\n" +
	"\rHANDSHAKE_RES\x10\x02\x12\r\n" +
	"\tNOTE_SYNC\x10\x03\x12\x11\n" +
	"\rFILE_TRANSFER\x10\x04\"\xb9\x01\n" +
	"\tHandshake\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12P\n" +
	"\x0fnote_timestamps\x18\x02 \x03(\v2'.peerflow.Handshake.NoteTimestampsEntryR\x0enoteTimestamps\x1aA\n" +
	"\x13NoteTimestampsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"z\n" +
	"\bNoteSync\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x04 \x01(\bR\tisDeleted\"\xa4\x01\n" +
	"\fFileTransfer\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12!\n" +
	"\fchunk_offset\x18\x04 \x01(\x03R\vchunkOffset\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x05 \x01(\fR\tchunkDataB\x17Z\x15peerflow/pkg/proto;pbb\x06proto3"

var (
	file_peerflow_proto_rawDescOnce sync.Once
	file_peerflow_proto_rawDescData []byte
)

func file_peerflow_proto_rawDescGZIP() []byte {
	file_peerflow_proto_rawDescOnce.Do(func() {
		file_peerflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peerflow_proto_rawDesc), len(file_peerflow_proto_rawDesc)))
	})
	return file_peerflow_proto_rawDescData
}

var file_peerflow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_peerflow_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_peerflow_proto_goTypes = []any{
	(Envelope_MessageType)(0), // 0: peerflow.Envelope.MessageType
	(*Envelope)(nil),          // 1: peerflow.Envelope
	(*Handshake)(nil),         // 2: peerflow.Handshake
	(*NoteSync)(nil),          // 3: peerflow.NoteSync
	(*FileTransfer)(nil),      // 4: peerflow.FileTransfer
	nil,                       // 5: peerflow.Handshake.NoteTimestampsEntry
}
var file_peerflow_proto_depIdxs = []int32{
	0, // 0: peerflow.Envelope.type:type_name -> peerflow.Envelope.MessageType
	5, // 1: peerflow.Handshake.note_timestamps:type_name -> peerflow.Handshake.NoteTimestampsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_peerflow_proto_init() }
func file_peerflow_proto_init() {
	if File_peerflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peerflow_proto_rawDesc), len(file_peerflow_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peerflow_proto_goTypes,
		DependencyIndexes: file_peerflow_proto_depIdxs,
		EnumInfos:         file_peerflow_proto_enumTypes,
		MessageInfos:      file_peerflow_proto_msgTypes,
	}.Build()
	File_peerflow_proto = out.File
	file_peerflow_proto_goTypes = nil
	file_peerflow_proto_depIdxs = nil
}
