// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNoteContent():Promise<string>;

export function GetPeerID():Promise<string>;

export function GetPeers():Promise<Array<string>>;

export function UpdateNote(arg1:string):Promise<void>;
