// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNoteContent() {
  return window['go']['main']['App']['GetNoteContent']();
}

export function GetPeerID() {
  return window['go']['main']['App']['GetPeerID']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function UpdateNote(arg1) {
  return window['go']['main']['App']['UpdateNote'](arg1);
}
